Massively simplified travis-ci build scripts.
Opted to rely on homebrew for OS X for cmake
Opted to rely on trusted ppa backport for Linux for cmake

Removed licenses that were now bigger than the entire scripts in most
cases. They're still CC0

diff --git a/scripts/travis-before-install b/scripts/travis-before-install
--- a/scripts/travis-before-install
+++ b/scripts/travis-before-install
@@ -1,25 +1,9 @@
 #!/bin/sh
-# Written in 2015 by MNMLSTC
-# To the extent possible under law, the author(s) have dedicated all copyright
-# and related and neighboring rights to this software to the public domain
-# worldwide. This software is distributed without any warranty. You should have
-# received a copy of the CC0 Public Domain Dedication along with this software.
-# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
+# travis-before-install - build-script
 
-VERSION=3.3.2
-URL=https://cmake.org/files/v3.3/cmake-$VERSION-$(uname -s)-x86_64.tar.gz
-
+# This is apparently an expected approach in the event brew update fails on
+# the first try. Wat.
 if [[ "Darwin" = $(uname -s) ]]; then
-  COMPONENTS=3
+  brew update || brew update || exit 1
+  brew upgrade
 fi
-
-function version { $HOME/cmake/bin/cmake --version | head -n1; }
-
-if [[ -d $HOME/cmake && $VERSION = $(version | sed s/[^0-9]*//) ]]; then
-  echo Using $(version) && exit 0
-fi
-
-curl $URL -o cmake.tar.gz || exit 1
-mkdir -p $HOME/cmake
-tar xzf cmake.tar.gz -C $HOME/cmake --strip-components=${COMPONENTS:-1}
-ls $HOME/cmake
